---
abstract: 'deploy via scp and ssh'
author:
  - chromatic
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ScpDeploy
requires:
  Dist::Zilla: 4.200007
version: 20110610.2306
