---
abstract: 'deploy via scp and ssh'
author:
  - chromatic
build_requires:
  Test::DZil: 0
  Test::Fatal: 0.006
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ScpDeploy
requires:
  Dist::Zilla: 4.200007
  Dist::Zilla::Role::Releaser: 0
  Moose: 2.0007
  Moose::Util::TypeConstraints: 0
  constant: 0
  namespace::autoclean: 0
version: 1.20110614
